consumer_key="YOUR_CONSUMER_KEY_HERE"
consumer_secret="YOUR_CONSUMER_SECRET_HERE"
oauth_token="YOUR_OAUTH_TOKEN_HERE"
oauth_token_secret="YOUR_OAUTH_TOKEN_SECRET_HERE"
bearer_token="YOUR_BEARER_TOKEN_HERE"
